name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: turtlebrowser/get-conan@main
      with:
        version: 1.66.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
